

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5053:5053"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - HOST=${HOST}
      - MODE=${MODE}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CODE_SEED=${CODE_SEED}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
